version: '3'
services:
  db:
    image: mysql
  web:
    build: .
    command: python¥3 manage.py runserver 0.0.0.0.8080
    volumes:
      - .:/app
    posts:
      - "8080:80"
    depends_on:
      - db
